
stages:
  - build
  - quick_tests
  - medium_size_tests

variables:
  bb5_build_dir: "pipeline"  # Notice: this keeps build dir among jobs! no artifacts needed
  bb5_account: proj12
  bb5_partition: prod_small
  bb5_cpus_per_task: 2
  RUN_PY_TESTS: "yes"
  SPACK_BRANCH: "ci/change_gitlab"
  TEST_VERSIONS: "neocortex"

default:
  tags:
    - bb5_map
  before_script:
    - export HOME="$(pwd)/BUILD_HOME"
    - export SPACK_ROOT="$HOME/spack"
    - export PATH="$SPACK_ROOT/bin:$PATH"
    - export TMPDIR="$TMPDIR/$CI_PIPELINE_ID"

build_neurodamus:
  stage: build
  variables:
    bb5_cpus_per_task: 16
    bb5_constraint: cpu
  script:
    - mkdir -p $HOME
    - ln -s ~bbpcihpcproj12/.ssh $HOME/
    - git config --global url."git@bbpgitlab.epfl.ch:hpc/".insteadOf "ssh://bbpcode.epfl.ch/"  # TODO: delete me
    - source ./.tests_setup.sh
    - install_neurodamus


## Generic test settings

.neurodamus_test:
  variables:
    GIT_STRATEGY: none
    bb5_constraint: cpu
  script:
    - source ./.tests_setup.sh
    - run_test $TESTNAME "${VERSIONS[$ND_VERSION]}"


## Neurodamus Quick tests

.neurodamus_test_quick:
  extends: .neurodamus_test
  stage: quick_tests
  variables:
    bb5_ntasks: 2
  #   TESTS_REUSE_ALLOCATION: "1"
  #   bb5_memory: 0
  #   bb5_ntasks: 36


q_neocortex:
  extends: .neurodamus_test_quick
  parallel:
    matrix:
#       - ND_VERSION: ncx_bare
#         TESTNAME: [quick-v5-gaps, quick-v6, quick-v5-multisplit, point-neuron]
#       - ND_VERSION: neocortex
#         TESTNAME: [quick-v5-multisplit, scx-1k-v5, scx-1k-v5-newparams, quick-1k-v5-nodesets, quick-scx-multi-circuit]
#       - ND_VERSION: ncx_plasticity
#         TESTNAME: quick-v5-plasticity
      - ND_VERSION: neocortex  # TODO: delete me
        TESTNAME: quick-v6

# q_hippocampus:
#   extends: .neurodamus_test_quick
#   parallel:
#     matrix:
#       - ND_VERSION: hippocampus
#         TESTNAME: [quick-hip-projSeed2, quick-hip-multipopulation, quick-hip-delayconn]

# q_other:
#   extends: .neurodamus_test_quick
#   parallel:
#     matrix:
#       - ND_VERSION: thalamus
#         TESTNAME: thalamus
#       - ND_VERSION: mousify
#         TESTNAME: quick-mousify-sonata


## Neurodamus Medium Size tests

# .neurodamus_medium-size_test:
#   extends: .neurodamus_test
#   stage: medium_size_tests

# neocortex:
#   extends: .neurodamus_medium-size_test
#   parallel:
#     matrix:
#       - ND_VERSION: neocortex
#         TESTNAME: [scx-v5-gapjunctions, scx-v5-bonus-minis]
#       - ND_VERSION: ncx_plasticity
#         TESTNAME: [scx-v5-plasticity, sscx-v7-plasticity]

# other-models:
#   extends: .neurodamus_medium-size_test
#   parallel:
#     matrix:
#       - ND_VERSION: hippocampus
#         TESTNAME: [hip-v6, hip-v6-mcr4]
#       - ND_VERSION: mousify
#         TESTNAME: mousify
